In [4]:
import pandas as pd

df = pd.DataFrame({
    'employee_id': [1, 1, 1, 2, 2, 2, 3, 3, 3],
    'month': ['2024-01', '2024-02', '2024-03',
              '2024-01', '2024-02', '2024-03',
              '2024-01', '2024-02', '2024-03'],
    'sales': [100, 150, 120, 200, 180, 220, 90, 95, 110],
    'target': [120, 120, 120, 200, 200, 200, 100, 100, 100]
})

df.head()

   employee_id    month  sales  target
0            1  2024-01    100     120
1            1  2024-02    150     120
2            1  2024-03    120     120
3            2  2024-01    200     200
4            2  2024-02    180     200

In [5]:
df['target_hit'] = df['sales'] > df['target']

df.head()

   employee_id    month  sales  target  target_hit
0            1  2024-01    100     120       False
1            1  2024-02    150     120        True
2            1  2024-03    120     120       False
3            2  2024-01    200     200       False
4            2  2024-02    180     200       False

In [9]:
df = df.sort_values(['employee_id','month'])

df['sales_prev'] = df.groupby('employee_id')['sales'].shift(1)

df.head()

   employee_id    month  sales  target  target_hit  sales_prev
0            1  2024-01    100     120       False         NaN
1            1  2024-02    150     120        True       100.0
2            1  2024-03    120     120       False       150.0
3            2  2024-01    200     200       False         NaN
4            2  2024-02    180     200       False       200.0

In [14]:
df['sales_growth'] = (df['sales'] / df['sales_prev']) * 100

df.head()

   employee_id    month  sales  target  target_hit  sales_prev  sales_growth
0            1  2024-01    100     120       False         NaN           NaN
1            1  2024-02    150     120        True       100.0         150.0
2            1  2024-03    120     120       False       150.0          80.0
3            2  2024-01    200     200       False         NaN           NaN
4            2  2024-02    180     200       False       200.0          90.0

In [16]:
df.groupby('employee_id')['target_hit'].agg('sum')

employee_id
1    1
2    1
3    1
Name: target_hit, dtype: int64

In [21]:
df.groupby('employee_id').agg(
    most_sales = ('sales', 'mean')
).idxmax()

most_sales    2
dtype: int64

In [22]:
import numpy as np

data = np.array([23, 45, 12, 67, 34, 89, 56, 78, 90, 11, 45, 67, 34, 56, 78])

In [24]:
data.mean()

np.float64(52.333333333333336)

In [30]:
np.median(data)

np.float64(56.0)

In [25]:
data.std()

np.float64(25.18376902336547)

In [ ]:
lower_limit = data.mean() - 2 * data.std()
higher_limit = data.mean() + 2 * data.std()

outlier = data[(data < lower_limit) | (data > higher_limit)]

In [57]:
min_max_scaler = ((data - data.min()) / (data.max() - data.min()))

min_max_scaler

array([0.15189873, 0.43037975, 0.01265823, 0.70886076, 0.29113924,
       0.98734177, 0.56962025, 0.84810127, 1.        , 0.        ,
       0.43037975, 0.70886076, 0.29113924, 0.56962025, 0.84810127])

In [56]:
IQR25 = np.percentile(data, 25)
IQR75 = np.percentile(data, 75)

In [46]:
Znormalizuje dane do zakresu 0-1 (min-max scaling) — bez sklearn, ręcznie
Policzy percentyl 25 i 75 (IQR)

IndexError: arrays used as indices must be of integer (or boolean) type