In [66]:
transactions = [
    {'id': 1, 'amount': 250, 'status': 'completed'},
    {'id': 2, 'amount': 1500, 'status': 'completed'},
    {'id': 3, 'amount': 80, 'status': 'failed'},
    {'id': 4, 'amount': 3000, 'status': 'completed'},
    {'id': 5, 'amount': 500, 'status': 'failed'},
]

In [67]:
def get_high_value_completed(x, threshold):
    a = [a['id'] for a in x if a['status'] == 'completed' and a['amount'] > threshold]
    return a

In [68]:
get_high_value_completed(transactions, 200)

[1, 2, 4]

In [80]:
import pandas as pd

df = pd.DataFrame({
    'seller': ['Anna', 'Anna', 'Anna', 'Bartek', 'Bartek', 'Celina'],
    'product': ['A', 'B', 'A', 'B', 'A', 'A'],
    'sales': [100, 200, 150, 300, 120, 400],
    'returned': [0, 1, 0, 0, 1, 0]
})

df.head()

   seller product  sales  returned
0    Anna       A    100         0
1    Anna       B    200         1
2    Anna       A    150         0
3  Bartek       B    300         0
4  Bartek       A    120         1

In [83]:
df.groupby('seller').agg(
    sum_sales=('sales', 'sum'),
    sum_returned=('returned', 'sum'),
    prc_returned=('returned', lambda x: x.sum() / x.count())
)

        sum_sales  sum_returned  prc_returned
seller
Anna          450             1      0.333333
Bartek        420             1      0.500000
Celina        400             0      0.000000

In [84]:
df_orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4, 5],
    'customer_id': [101, 102, 101, 103, 102],
    'amount': [250, 180, 320, 90, 410]
})

df_customers = pd.DataFrame({
    'customer_id': [101, 102, 104],
    'name': ['Anna', 'Bartek', 'Celina'],
    'city': ['Warsaw', 'Krakow', 'Gdansk']
})

In [89]:
merged_1 = pd.merge(df_orders, df_customers, on='customer_id', how='inner')

merged_1.head()

   order_id  customer_id  amount    name    city
0         1          101     250    Anna  Warsaw
1         2          102     180  Bartek  Krakow
2         3          101     320    Anna  Warsaw
3         5          102     410  Bartek  Krakow

In [88]:
merged_2 = pd.merge(df_orders, df_customers, on='customer_id', how='left')

merged_2.head()

   order_id  customer_id  amount    name    city
0         1          101     250    Anna  Warsaw
1         2          102     180  Bartek  Krakow
2         3          101     320    Anna  Warsaw
3         4          103      90     NaN     NaN
4         5          102     410  Bartek  Krakow

In [106]:
df_sales3 = pd.DataFrame({
    'seller': ['Anna', 'Anna', 'Anna', 'Bartek', 'Bartek', 'Bartek'],
    'month': ['2024-01', '2024-02', '2024-03', '2024-01', '2024-02', '2024-03'],
    'sales': [100, 120, 90, 200, 180, 220]
})

df_sales3.head()

   seller    month  sales
0    Anna  2024-01    100
1    Anna  2024-02    120
2    Anna  2024-03     90
3  Bartek  2024-01    200
4  Bartek  2024-02    180

In [107]:
df_sales3['sales_prev'] = df_sales3.groupby('seller')['sales'].shift(1)
df_sales3['sales_diff'] = df_sales3['sales'] - df_sales3['sales_prev']
df_sales3['is_better'] = df_sales3['sales_diff'] > 0

df_sales3.head()

   seller    month  sales  sales_prev  sales_diff  is_better
0    Anna  2024-01    100         NaN         NaN      False
1    Anna  2024-02    120       100.0        20.0       True
2    Anna  2024-03     90       120.0       -30.0      False
3  Bartek  2024-01    200         NaN         NaN      False
4  Bartek  2024-02    180       200.0       -20.0      False