In [6]:
import pandas as pd

df = pd.DataFrame({
    'name': ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa'],
    'department': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'salary': [5000, 3000, 7000, 4500, 6000],
    'years_experience': [3, 5, 8, 2, 6]
})

In [7]:
df.head()

     name department  salary  years_experience
0    Anna         IT    5000                 3
1  Bartek         HR    3000                 5
2  Celina         IT    7000                 8
3   Darek         HR    4500                 2
4     Ewa         IT    6000                 6

In [18]:
df_filtered = df[df['department'] == 'IT']
df_filtered.head()

     name department  salary  years_experience
0    Anna         IT    5000                 3
2  Celina         IT    7000                 8
4     Ewa         IT    6000                 6

In [22]:
avg_salary = df_filtered['salary'].mean()
print(avg_salary)

6000.0

In [23]:
avg_ye_exp = df_filtered['years_experience'].mean()
print(avg_ye_exp)

5.666666666666667

In [24]:
df_filtered[['salary','years_experience']].mean()

salary              6000.000000
years_experience       5.666667
dtype: float64

In [44]:
df.groupby('department').agg(
    srednia = ('salary','mean'),
    max_experience = ('years_experience','max'),
    number_of_emplyess = ('name', 'count')
)

            srednia  max_experience  number_of_emplyess
department
HR           3750.0               5                   2
IT           6000.0               8                   3

In [56]:
df_sales = pd.DataFrame({
    'month': ['2024-01', '2024-02', '2024-03', '2024-04', '2024-05'],
    'sales': [100, 120, 90, 150, 130]
})

df_sales.head()

     month  sales
0  2024-01    100
1  2024-02    120
2  2024-03     90
3  2024-04    150
4  2024-05    130

In [58]:
df_sales['sales_prev'] = df_sales['sales'].shift(1).fillna('Brak')
df_sales['sales_diff'] = df_sales['sales'] - df_sales['sales'].shift(1)

df_sales.head()

     month  sales sales_prev  sales_diff
0  2024-01    100       Brak         NaN
1  2024-02    120      100.0        20.0
2  2024-03     90      120.0       -30.0
3  2024-04    150       90.0        60.0
4  2024-05    130      150.0       -20.0

In [59]:
df_sales2 = pd.DataFrame({
    'seller': ['Anna', 'Anna', 'Anna', 'Bartek', 'Bartek', 'Bartek'],
    'month': ['2024-01', '2024-02', '2024-03', '2024-01', '2024-02', '2024-03'],
    'sales': [100, 120, 90, 200, 180, 220]
})

df_sales2.head()

   seller    month  sales
0    Anna  2024-01    100
1    Anna  2024-02    120
2    Anna  2024-03     90
3  Bartek  2024-01    200
4  Bartek  2024-02    180

In [63]:
df_sales2['sales_prev '] = df_sales2.groupby('seller')['sales'].shift(1)

df_sales2.head()

   seller    month  sales  sales_prev
0    Anna  2024-01    100          NaN
1    Anna  2024-02    120        100.0
2    Anna  2024-03     90        120.0
3  Bartek  2024-01    200          NaN
4  Bartek  2024-02    180        200.0