In [34]:
products = [
    {'name': 'laptop', 'price': 3500, 'category': 'electronics'},
    {'name': 'phone', 'price': 2000, 'category': 'electronics'},
    {'name': 'desk', 'price': 800, 'category': 'furniture'},
    {'name': 'chair', 'price': 400, 'category': 'furniture'},
    {'name': 'tablet', 'price': 1500, 'category': 'electronics'},
]

In [36]:
a = [x['name'] for x in products if x['category']=='electronics']
print(a)

['laptop', 'phone', 'tablet']

In [38]:
b = {x['name']:x['price'] for x in products if x['price']>1000}
print(b)

{'laptop': 3500, 'phone': 2000, 'tablet': 1500}

In [39]:
c = sorted(products, key=lambda x: x['price'], reverse=True)
print(c)

[{'name': 'laptop', 'price': 3500, 'category': 'electronics'}, {'name': 'phone', 'price': 2000, 'category': 'electronics'}, {'name': 'tablet', 'price': 1500, 'category': 'electronics'}, {'name': 'desk', 'price': 800, 'category': 'furniture'}, {'name': 'chair', 'price': 400, 'category': 'furniture'}]

In [63]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2024-01-10', '2024-01-15', '2024-02-05', '2024-02-20',
             '2024-03-01', '2024-03-15', '2024-03-28'],
    'product': ['laptop', 'phone', 'laptop', 'tablet',
                'phone', 'laptop', 'tablet'],
    'sales': [3500, 2000, 3500, 1500, 2000, 3500, 1500],
    'units': [2, 5, 1, 3, 4, 2, 6]
})

In [64]:
df.head()

         date product  sales  units
0  2024-01-10  laptop   3500      2
1  2024-01-15   phone   2000      5
2  2024-02-05  laptop   3500      1
3  2024-02-20  tablet   1500      3
4  2024-03-01   phone   2000      4

In [65]:
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month
df['revenue'] = df['sales'] * df['units']
print(df)

        date product  sales  units  month  revenue
0 2024-01-10  laptop   3500      2      1     7000
1 2024-01-15   phone   2000      5      1    10000
2 2024-02-05  laptop   3500      1      2     3500
3 2024-02-20  tablet   1500      3      2     4500
4 2024-03-01   phone   2000      4      3     8000
5 2024-03-15  laptop   3500      2      3     7000
6 2024-03-28  tablet   1500      6      3     9000

In [74]:
df_grouped = df.groupby(['month', 'product']).agg({'revenue': 'sum', 'units': 'sum'}).reset_index()
print(df_grouped)

   month product  revenue  units
0      1  laptop     7000      2
1      1   phone    10000      5
2      2  laptop     3500      1
3      2  tablet     4500      3
4      3  laptop     7000      2
5      3   phone     8000      4
6      3  tablet     9000      6

In [73]:
product_revenue = df.groupby('product')['revenue'].sum()
best_product = product_revenue.idxmax()
print(best_product)

phone

In [153]:
import pandas as pd

df_sales = pd.DataFrame({
    'seller_id': [1, 1, 1, 2, 2, 2, 3, 3, 3],
    'month': ['2024-01', '2024-02', '2024-03',
              '2024-01', '2024-02', '2024-03',
              '2024-01', '2024-02', '2024-03'],
    'revenue': [10000, 12000, 9000, 15000, 14000, 16000, 8000, 9000, 11000]
})

df_sellers = pd.DataFrame({
    'seller_id': [1, 2, 3],
    'name': ['Anna', 'Bartek', 'Celina'],
    'region': ['North', 'South', 'North']
})

In [154]:
df_merged = pd.merge(df_sales, df_sellers, on='seller_id', how='left')
print(df_merged)

   seller_id    month  revenue    name region
0          1  2024-01    10000    Anna  North
1          1  2024-02    12000    Anna  North
2          1  2024-03     9000    Anna  North
3          2  2024-01    15000  Bartek  South
4          2  2024-02    14000  Bartek  South
5          2  2024-03    16000  Bartek  South
6          3  2024-01     8000  Celina  North
7          3  2024-02     9000  Celina  North
8          3  2024-03    11000  Celina  North

In [155]:
df_merged = df_merged.sort_values(by=['seller_id', 'month'])
df_merged['revenue_prev'] = df_merged.groupby('seller_id')['revenue'].shift(1)
df_merged['growth'] = df_merged.groupby('seller_id')['revenue'].pct_change() * 100
print(df_merged)

   seller_id    month  revenue    name region  revenue_prev     growth
0          1  2024-01    10000    Anna  North           NaN        NaN
1          1  2024-02    12000    Anna  North       10000.0  20.000000
2          1  2024-03     9000    Anna  North       12000.0 -25.000000
3          2  2024-01    15000  Bartek  South           NaN        NaN
4          2  2024-02    14000  Bartek  South       15000.0  -6.666667
5          2  2024-03    16000  Bartek  South       14000.0  14.285714
6          3  2024-01     8000  Celina  North           NaN        NaN
7          3  2024-02     9000  Celina  North        8000.0  12.500000
8          3  2024-03    11000  Celina  North        9000.0  22.222222

In [156]:
df_avg_region = df_merged.groupby('region')['revenue'].mean().reset_index()
print(df_avg_region)

  region       revenue
0  North   9833.333333
1  South  15000.000000

In [159]:
#need to find a months when every seller had growth > 0
df_filtered = df_merged[df_merged['growth'] > 0]
counts = df_filtered.groupby('month')['seller_id'].count()
counts[counts==3]

Series([], Name: seller_id, dtype: int64)

In [158]:
print(df_merged[['name', 'month', 'revenue', 'revenue_prev', 'growth']])

     name    month  revenue  revenue_prev     growth
0    Anna  2024-01    10000           NaN        NaN
1    Anna  2024-02    12000       10000.0  20.000000
2    Anna  2024-03     9000       12000.0 -25.000000
3  Bartek  2024-01    15000           NaN        NaN
4  Bartek  2024-02    14000       15000.0  -6.666667
5  Bartek  2024-03    16000       14000.0  14.285714
6  Celina  2024-01     8000           NaN        NaN
7  Celina  2024-02     9000        8000.0  12.500000
8  Celina  2024-03    11000        9000.0  22.222222

In [170]:
import pandas as pd

df_orders = pd.DataFrame({
    'order_id': range(1, 10),
    'customer_id': [1, 1, 1, 2, 2, 2, 3, 3, 3],
    'month': ['2024-01', '2024-02', '2024-03',
              '2024-01', '2024-02', '2024-03',
              '2024-01', '2024-02', '2024-03'],
    'amount': [500, 700, 600, 1000, 900, 1100, 300, 350, 400]
})

df_customers = pd.DataFrame({
    'customer_id': [1, 2, 3],
    'name': ['Anna', 'Bartek', 'Celina'],
    'segment': ['premium', 'premium', 'standard']
})

In [173]:
df_merged_orders = pd.merge(df_orders, df_customers, on='customer_id', how='left')
df_merged_orders.head()

   order_id  customer_id    month  amount    name  segment
0         1            1  2024-01     500    Anna  premium
1         2            1  2024-02     700    Anna  premium
2         3            1  2024-03     600    Anna  premium
3         4            2  2024-01    1000  Bartek  premium
4         5            2  2024-02     900  Bartek  premium

In [177]:
df_merged_orders['amount_prev'] = df_merged_orders.groupby('customer_id')['amount'].shift(1)
df_merged_orders['growth'] = df_merged_orders.groupby('customer_id')['amount'].pct_change() * 100
df_merged_orders.head()

,order_id,customer_id,month,amount,name,segment,amount_prev,growth
0,1,1,2024-01,500,Anna,premium,NaN,NaN
1,2,1,2024-02,700,Anna,premium,500.0,40.000000
2,3,1,2024-03,600,Anna,premium,700.0,-14.285714
3,4,2,2024-01,1000,Bartek,premium,NaN,NaN
4,5,2,2024-02,900,Bartek,premium,1000.0,-10.000000

In [178]:
df_merged_orders_avg_segment = df_merged_orders.groupby('segment')['amount'].mean().reset_index()
df_merged_orders_avg_segment

    segment  amount
0   premium   800.0
1  standard   350.0

In [189]:
df_merged_growth_filtered = df_merged_orders[df_merged_orders['growth'] > 0]
counts = df_merged_growth_filtered.groupby('customer_id')['month'].count()
n_months = 2 
winning_customers = counts[counts == n_months]
winning_customers

customer_id
3    2
Name: month, dtype: int64