In [1]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2024-01-05', '2024-01-20', '2024-02-10', '2024-02-25',
             '2024-03-05', '2024-03-20', '2024-01-10', '2024-02-15',
             '2024-03-10', '2024-03-25'],
    'product_id': [1, 1, 1, 1, 1, 1, 2, 2, 2, 2],
    'category': ['electronics', 'electronics', 'electronics', 'electronics',
                 'electronics', 'electronics', 'furniture', 'furniture',
                 'furniture', 'furniture'],
    'revenue': [5000, 6000, 4500, 7000, 5500, 6500, 2000, 2500, 1800, 3000],
    'units': [2, 3, 2, 4, 3, 3, 5, 6, 4, 7]
})

In [2]:
df.head()

         date  product_id     category  revenue  units
0  2024-01-05           1  electronics     5000      2
1  2024-01-20           1  electronics     6000      3
2  2024-02-10           1  electronics     4500      2
3  2024-02-25           1  electronics     7000      4
4  2024-03-05           1  electronics     5500      3

In [4]:
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.to_period('M')
df['avg_price'] = df['revenue'] / df['units']
df.head()

        date  product_id     category  revenue  units    avg_price    month
0 2024-01-05           1  electronics     5000      2  2500.000000  2024-01
1 2024-01-20           1  electronics     6000      3  2000.000000  2024-01
2 2024-02-10           1  electronics     4500      2  2250.000000  2024-02
3 2024-02-25           1  electronics     7000      4  1750.000000  2024-02
4 2024-03-05           1  electronics     5500      3  1833.333333  2024-03

In [8]:
df_grouped = df.groupby(['product_id', 'month']).agg({
    'revenue': 'sum',
    'units': 'sum',
    'avg_price': 'mean'
})
df_grouped

                    revenue  units    avg_price
product_id month
1          2024-01    11000      5  2250.000000
           2024-02    11500      6  2000.000000
           2024-03    12000      6  2000.000000
2          2024-01     2000      5   400.000000
           2024-02     2500      6   416.666667
           2024-03     4800     11   439.285714

In [20]:
df = df.sort_values(by=['product_id', 'date'])
df['revenue_prev'] = df.groupby('product_id')['revenue'].shift(1)
df['revenue_growth'] = df.groupby('product_id')['revenue'].pct_change() * 100
df.head()

,date,product_id,category,revenue,units,avg_price,month,revenue_prev,revenue_growth
0,2024-01-05,1,electronics,5000,2,2500.000000,2024-01,NaN,NaN
1,2024-01-20,1,electronics,6000,3,2000.000000,2024-01,5000.0,20.000000
2,2024-02-10,1,electronics,4500,2,2250.000000,2024-02,6000.0,-25.000000
3,2024-02-25,1,electronics,7000,4,1750.000000,2024-02,4500.0,55.555556
4,2024-03-05,1,electronics,5500,3,1833.333333,2024-03,7000.0,-21.428571

In [27]:
df_category_sum_revenue = df.groupby('category')['revenue'].sum()
final = df_category_sum_revenue.idxmax()
final

'electronics'

In [33]:
df_average_month = df.groupby('month')['avg_price'].mean().reset_index()
df_average_month_max = df_average_month[df_average_month['avg_price'] == df_average_month['avg_price'].max()]
df_average_month_max

     month    avg_price
0  2024-01  1633.333333